### ISSUE TITLE
Player-GO repeat automatically toggles off after a song track set to repeat is done playing.

### ISSUE THREAD

**Issue by kodeblacc** [STWheel/Player-GO#1]
#### Expected behavior
The repeat function which is common in all music players serves to put a song playing on repeat. The expected behavior of the repeat function on Player-Go is to maintain the song playing on repeat till it is toggled off by the user.
#### Actual behavior
The repeat function automatically toggles off after the music that was set to repeat has finished playing. Although the song is still played again but after the time elapses, the next song in the album is played.
#### How to reproduce
- Launch the app
- Open an album with at least two tracks
- play any of the tracks on the album
- turn on the repeat function
- allow the track to play till the end(catalyze this action with the seekbar)
- as soon as the track is done playing, the repeat function goes off.
* App name/App version: Player-Go v1.0
* Operating system:  Android 7.0
#### Recording Of The Bug
https://youtu.be/vDIjF_V6gtM

**Comment by STWheel** [comment]
Dear @kodeblacc
Thank you for the comment.
One click on the repeat button implements only one next repetition of this song. When this song automatically starts again start the repeat symbol will be deactivated. The function of an infinite repetition of the song is absent in Player-GO and in the its prototype (Music-Player-GO) also.
